---
- name: Prompt playbook
  hosts: all
  vars_prompt:
     - name: username
       prompt: Enter you user name
       private: False
       default: Trilok
     - name: password
       prompt: Enter password
       private: True
       encrypt: sha512_crypt
       salt_size: 7

  tasks:
     - name: Your user name and password
       debug:
          msg: "{{ username }} = = = {{ password }}"
