---
- name: Update Web Servers
  hosts: all

  tasks:
    - name: Ensure Apache is present
      apt: 
         name: apache2
         state: latest
         update_cache: yes 

    - name: Write the apache index.html
      template:
        src: /home/devops/ANSIBLE/templates/index.html
        dest: /var/www/html/index.html

- name: Update DB servers
  hosts: all

  tasks:
    - name: Ensure Postgresql is present
      apt: 
         name: postgresql
         state: latest

    - name: Ensure postgresql is started
      service: 
         name: postgresql
         state: started 

